name: 04 - Using Actions
on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          path: '.'
      - name: Printing Folders
        run: |
          ls -lah .
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
            node-version: '20.x'
      - name: Install Dependencies
        working-directory: 04-using-actions/react-app
        run: |
          ls -lah
          npm ci
           
          
          