name: 09 - Using Functions
on:
  # pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: |
          echo "exit -1"
      - name: Print PR title
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.pull_request.title }}"
          echo "${{ toJson(github.event.pull_request) }}"
      - name: Print PR labels
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ toJson(github.event.pull_request.labels) }}"
          echo "${{ github.event.pull_request.labels }}"
      - name: Print PR labels v2
        if: github.event_name == 'pull_request'
        run: | 
              cat << EOF
              ${{ toJSON(github.event.pull_request.labels) }}
              EOF
      - name: Bug step
        if: ${{
                github.event_name == 'pull_request' 
                && failure() 
                && !cancelled() 
                && contains(github.event.pull_request.title, 'fix')
            }}
        run: |
          echo "I am a bug fix"
      - name: Sleep for 20 seconds
        run: sleep 20
      - name: I will be skipped
        if: ${{ success() }}
        run: |
          echo "I will print if previous steps succeed."
      - name: I will execute
        if: ${{ failure() }}  
        run: |
          echo "I will print if any previous step fails."
      - name: I will execute
        if: ${{ !cancelled() }}  
        run: |
          echo "I will always print, except when the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}  
        run: |
          echo "I will always print, except when the workflow is cancelled."
          

