name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ${{matrix.os}}
    name: ${{matrix.os}}-${{matrix.node}}
    strategy:
      # fail-fast: true
      matrix:
        include:
          - node: 16.x
            os: ubuntu-latest
          - node: 21.x
            os: ubuntu-latest
            tag: experimental
        node: [18, 20, 21.x]
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{matrix.node}}
      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: exit -1
      - name: Perform some tests
        run: | 
          sleep 10
          echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node}}"
      - name: Upload test results
        run: | 
          echo "Uploading test results"
